### ISSUE TITLE
Dostupnost a nedostupnost lidí

### ISSUE THREAD

**Issue by ptakopysk** [ufal/THEaiTRE#12]
Tracking toho kdo je jak dostupný či nedostupný.

**Comment by ptakopysk** [comment]
Tom Kocmi je celý březen nedostupný (Velký Bratr).

**Comment by ptakopysk** [comment]
Máša Nováková je nedostupná do 2. března.

**Comment by tuetschek** [comment]
Nebude jednodušší doodle? https://doodle.com/poll/n3qnc2t54b9kesnb

**Comment by ptakopysk** [comment]
Jo, Doodle asi taky dobrej, dík... ale zatím nemáme nic nového, takže bych na to zbytečně nespěchal :-)

**Comment by ptakopysk** [comment]
Info od Mášy zatím na první týden března:

Zdravím,
já můžu:
2. 3. kdykoli
3. 3. celý den do 19:00
4. 3. kdykoli
5. 3. od 12ti
Máša

**Comment by ptakopysk** [comment]
Tomáš Musil prý nemá ještě tenhle týden čas, pak snad jo.
