### ISSUE TITLE
Vygenerovat GPT-2 výstupy pro vstupy od DAMU

### ISSUE THREAD

**Issue by ptakopysk** [ufal/THEaiTRE#14]
DAMU připravilo 6 inputů, jsou zde: `/net/projects/theaitre/inputs_damu_01/`
Pokyn je: "chce to tedy krátké repliky, a pouze dvě mluvící a střídající se postavy".
Je tedy potřeba tyhle vstupy naládovat do GPT-2 a výstupy pak dát k dispozici DAMákum.
Ideálně by zároveň bylo vhodné omezit počet postav a délku replik ve vygenerovaném výstupu, ale lepší mít brzo něco suboptimálního než mít optimální výsledky ale až za měsíc.

**Comment by djurkis** [comment]
v /lnet/ms/projects/URU/dominik/damu_samples su CS a ENG verzie toho co vygenerovalo gpt , pouzil som skript gen_samples.sh , v najblizsej dobe sa pokusim to nejako ohnut aby sa obmedzil pocet postav , dlzka  replik a ?repetitivnost?

**Comment by ptakopysk** [comment]
Postup:
- dát input propmt ukončenej postavou: "Petr: blablabla.\n\nHonza: blabla.\n\nPetr:"
-  z výstupu to vzít až do další postavy/do dalšího prázdného řádku/?
- repliku přilípnout ke vstupu, zbytek zahodit, a iterovat
- omezená délka: řešit opakovaným samplováním, dokud to nebude dost krátký

**Comment by tomasmcz** [comment]
něco jsem vygeneroval do `gpt2/samples`

**Comment by ptakopysk** [comment]
Oproti tomu co generoval Dominik je tohle citelně horší. Zejména se tam nmohem víc opakují věci vykopírované přímo ze vstupu. A související: často se tam obecně opakují stejné části.
